apiVersion: apps/v1
kind: Deployment
metadata:
  name: immovables-serverside-deployment
  namespace: ns-immovables
spec:
  replicas: 3
  selector:
    matchLabels:
      app: immovables-serverside
  template:
    metadata:
      labels:
        app: immovables-serverside
    spec:
      containers:
        - name: immovables-serverside
          image: och5351/expresstest:latest
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
          env:
            - name: DATE
              value: 'DATE_STRING'
      #imagePullSecrets:
      #  - name: my-secret
      nodeSelector:
        kubernetes.io/hostname: och2