server:
  # port: 3000
  servlet:
    context-path: /

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    mongodb:
      uri: mongodb://opyter.iptime.org:27017/crawler
      database: crawler
  session:
    timeout: 600
    store-type: mongodb
    mongodb:
      collection-name: sessions
  datasource:
    url: jdbc:mariadb://opyter.iptime.org:13306/Immovables
    driver-class-name: org.mariadb.jdbc.Driver
    username: och
    password: WEstart03@(
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    #database: mariadb
    hibernate:
      ddl-auto: update

# JWT
jwt:
  secret: "bearar"
  access-expired: 3600 # 30(분) - 단위 (초)

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
